spring:
  application:
    name: foundation-system

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/general_givers}
    username: ${SPRING_DATASOURCE_USERNAME:peter}
    password: ${SPRING_DATASOURCE_PASSWORD:manu}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com.generalgivers: INFO
    org.springframework.web: INFO
    org.hibernate: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

app:
  jwt:
    secret: ${JWT_SECRET:your_secure_random_secret_key_minimum_256_bits_for_HS256_algorithm}
    expiration: 900000  # 15 minutes in milliseconds
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:3000}

    daraja:
      consumer-key: 7yZE5AcPP7dNIsyYfDAYVFCgTdyKBSWO73luWOkWFlCp27Az
      consumer-secret: aVCb7k7nFeR4mODHj779lG94RFY3ipcNI6xdS5CQHJhnGPI8E8Ub5QmWGQA4KODZ
      short-code: 174379
      passkey: KXZphPvbhbxcJtIeCkwgUmujKcJTlVX+/KbyCnKnNgRyVltcMEzlgDo62CIh1dKIZ8Ng9yjhV8bJGUBM180zH5nCVp9WAAHpG3aqLWbyrICPwiPNu/Zf/swYsoob3vxNNk+oN2MAa8cuVRQ1YDrBsOezpcKqOVn9aPSupuyJCkPW2e0/JlM2/oMAkE9JQKZ2TTZkVsJFHWoJZzp6wPlgOz29x6V8UWFjstdahk5DzcpPAZPabH4biXEIYSKi1Y3b6HvnkJ0JtGWMW48Oig8uWrPuvk5bub7qP7BfC4y15JH6r2rIBiOt0OsAXcmqjG57Wcp5lT5vReQTGe07vtwx0A==
      callback-url: https://yourdomain.com/api/mpesa/callback
      base-url: https://sandbox.safaricom.co.ke
